name: deploy

on: 
  push:
    main:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14'
          cache: 'npm'
      - name: Install npm@8
        run: npm i -g npm@8
      - name: Install
        run: npm ci --prefer-offline
      - name: Build
        run: npm run build